// Generated by gencpp from file upros_message/Adc.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_ADC_H
#define UPROS_MESSAGE_MESSAGE_ADC_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upros_message
{
template <class ContainerAllocator>
struct Adc_
{
  typedef Adc_<ContainerAllocator> Type;

  Adc_()
    : ad1(0)
    , ad2(0)
    , ad3(0)
    , ad4(0)
    , ad5(0)
    , ad6(0)
    , ad7(0)
    , ad8(0)
    , ad9(0)
    , ad10(0)
    , ad11(0)
    , ad12(0)  {
    }
  Adc_(const ContainerAllocator& _alloc)
    : ad1(0)
    , ad2(0)
    , ad3(0)
    , ad4(0)
    , ad5(0)
    , ad6(0)
    , ad7(0)
    , ad8(0)
    , ad9(0)
    , ad10(0)
    , ad11(0)
    , ad12(0)  {
  (void)_alloc;
    }



   typedef int16_t _ad1_type;
  _ad1_type ad1;

   typedef int16_t _ad2_type;
  _ad2_type ad2;

   typedef int16_t _ad3_type;
  _ad3_type ad3;

   typedef int16_t _ad4_type;
  _ad4_type ad4;

   typedef int16_t _ad5_type;
  _ad5_type ad5;

   typedef int16_t _ad6_type;
  _ad6_type ad6;

   typedef int16_t _ad7_type;
  _ad7_type ad7;

   typedef int16_t _ad8_type;
  _ad8_type ad8;

   typedef int16_t _ad9_type;
  _ad9_type ad9;

   typedef int16_t _ad10_type;
  _ad10_type ad10;

   typedef int16_t _ad11_type;
  _ad11_type ad11;

   typedef int16_t _ad12_type;
  _ad12_type ad12;





  typedef boost::shared_ptr< ::upros_message::Adc_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upros_message::Adc_<ContainerAllocator> const> ConstPtr;

}; // struct Adc_

typedef ::upros_message::Adc_<std::allocator<void> > Adc;

typedef boost::shared_ptr< ::upros_message::Adc > AdcPtr;
typedef boost::shared_ptr< ::upros_message::Adc const> AdcConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upros_message::Adc_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upros_message::Adc_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upros_message::Adc_<ContainerAllocator1> & lhs, const ::upros_message::Adc_<ContainerAllocator2> & rhs)
{
  return lhs.ad1 == rhs.ad1 &&
    lhs.ad2 == rhs.ad2 &&
    lhs.ad3 == rhs.ad3 &&
    lhs.ad4 == rhs.ad4 &&
    lhs.ad5 == rhs.ad5 &&
    lhs.ad6 == rhs.ad6 &&
    lhs.ad7 == rhs.ad7 &&
    lhs.ad8 == rhs.ad8 &&
    lhs.ad9 == rhs.ad9 &&
    lhs.ad10 == rhs.ad10 &&
    lhs.ad11 == rhs.ad11 &&
    lhs.ad12 == rhs.ad12;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upros_message::Adc_<ContainerAllocator1> & lhs, const ::upros_message::Adc_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upros_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upros_message::Adc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upros_message::Adc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::Adc_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::Adc_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::Adc_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::Adc_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upros_message::Adc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fa8ac5d6495ff0c6b2c630d498ca618";
  }

  static const char* value(const ::upros_message::Adc_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fa8ac5d6495ff0cULL;
  static const uint64_t static_value2 = 0x6b2c630d498ca618ULL;
};

template<class ContainerAllocator>
struct DataType< ::upros_message::Adc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upros_message/Adc";
  }

  static const char* value(const ::upros_message::Adc_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upros_message::Adc_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 ad1\n"
"int16 ad2\n"
"int16 ad3\n"
"int16 ad4\n"
"int16 ad5\n"
"int16 ad6\n"
"int16 ad7\n"
"int16 ad8\n"
"int16 ad9\n"
"int16 ad10\n"
"int16 ad11\n"
"int16 ad12\n"
;
  }

  static const char* value(const ::upros_message::Adc_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upros_message::Adc_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ad1);
      stream.next(m.ad2);
      stream.next(m.ad3);
      stream.next(m.ad4);
      stream.next(m.ad5);
      stream.next(m.ad6);
      stream.next(m.ad7);
      stream.next(m.ad8);
      stream.next(m.ad9);
      stream.next(m.ad10);
      stream.next(m.ad11);
      stream.next(m.ad12);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Adc_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upros_message::Adc_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upros_message::Adc_<ContainerAllocator>& v)
  {
    s << indent << "ad1: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ad1);
    s << indent << "ad2: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ad2);
    s << indent << "ad3: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ad3);
    s << indent << "ad4: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ad4);
    s << indent << "ad5: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ad5);
    s << indent << "ad6: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ad6);
    s << indent << "ad7: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ad7);
    s << indent << "ad8: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ad8);
    s << indent << "ad9: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ad9);
    s << indent << "ad10: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ad10);
    s << indent << "ad11: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ad11);
    s << indent << "ad12: ";
    Printer<int16_t>::stream(s, indent + "  ", v.ad12);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_ADC_H
