// Generated by gencpp from file upros_message/TagCommand.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_TAGCOMMAND_H
#define UPROS_MESSAGE_MESSAGE_TAGCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace upros_message
{
template <class ContainerAllocator>
struct TagCommand_
{
  typedef TagCommand_<ContainerAllocator> Type;

  TagCommand_()
    : intent()
    , target(0)  {
    }
  TagCommand_(const ContainerAllocator& _alloc)
    : intent(_alloc)
    , target(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _intent_type;
  _intent_type intent;

   typedef int32_t _target_type;
  _target_type target;





  typedef boost::shared_ptr< ::upros_message::TagCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upros_message::TagCommand_<ContainerAllocator> const> ConstPtr;

}; // struct TagCommand_

typedef ::upros_message::TagCommand_<std::allocator<void> > TagCommand;

typedef boost::shared_ptr< ::upros_message::TagCommand > TagCommandPtr;
typedef boost::shared_ptr< ::upros_message::TagCommand const> TagCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upros_message::TagCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upros_message::TagCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upros_message::TagCommand_<ContainerAllocator1> & lhs, const ::upros_message::TagCommand_<ContainerAllocator2> & rhs)
{
  return lhs.intent == rhs.intent &&
    lhs.target == rhs.target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upros_message::TagCommand_<ContainerAllocator1> & lhs, const ::upros_message::TagCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upros_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upros_message::TagCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upros_message::TagCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::TagCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::TagCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::TagCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::TagCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upros_message::TagCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f5d3d8704f9102c2cbffcd5d0f7f7574";
  }

  static const char* value(const ::upros_message::TagCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf5d3d8704f9102c2ULL;
  static const uint64_t static_value2 = 0xcbffcd5d0f7f7574ULL;
};

template<class ContainerAllocator>
struct DataType< ::upros_message::TagCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upros_message/TagCommand";
  }

  static const char* value(const ::upros_message::TagCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upros_message::TagCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string intent  \n"
"int32 target  \n"
;
  }

  static const char* value(const ::upros_message::TagCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upros_message::TagCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.intent);
      stream.next(m.target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TagCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upros_message::TagCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upros_message::TagCommand_<ContainerAllocator>& v)
  {
    s << indent << "intent: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.intent);
    s << indent << "target: ";
    Printer<int32_t>::stream(s, indent + "  ", v.target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_TAGCOMMAND_H
