// Generated by gencpp from file upros_message/YoloDetection.msg
// DO NOT EDIT!


#ifndef UPROS_MESSAGE_MESSAGE_YOLODETECTION_H
#define UPROS_MESSAGE_MESSAGE_YOLODETECTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace upros_message
{
template <class ContainerAllocator>
struct YoloDetection_
{
  typedef YoloDetection_<ContainerAllocator> Type;

  YoloDetection_()
    : header()
    , seq(0)
    , stamp()
    , frame_id()
    , class_id(0)
    , center_x(0)
    , center_y(0)  {
    }
  YoloDetection_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , seq(0)
    , stamp()
    , frame_id(_alloc)
    , class_id(0)
    , center_x(0)
    , center_y(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _seq_type;
  _seq_type seq;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _frame_id_type;
  _frame_id_type frame_id;

   typedef int32_t _class_id_type;
  _class_id_type class_id;

   typedef int32_t _center_x_type;
  _center_x_type center_x;

   typedef int32_t _center_y_type;
  _center_y_type center_y;





  typedef boost::shared_ptr< ::upros_message::YoloDetection_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::upros_message::YoloDetection_<ContainerAllocator> const> ConstPtr;

}; // struct YoloDetection_

typedef ::upros_message::YoloDetection_<std::allocator<void> > YoloDetection;

typedef boost::shared_ptr< ::upros_message::YoloDetection > YoloDetectionPtr;
typedef boost::shared_ptr< ::upros_message::YoloDetection const> YoloDetectionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::upros_message::YoloDetection_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::upros_message::YoloDetection_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::upros_message::YoloDetection_<ContainerAllocator1> & lhs, const ::upros_message::YoloDetection_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.seq == rhs.seq &&
    lhs.stamp == rhs.stamp &&
    lhs.frame_id == rhs.frame_id &&
    lhs.class_id == rhs.class_id &&
    lhs.center_x == rhs.center_x &&
    lhs.center_y == rhs.center_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::upros_message::YoloDetection_<ContainerAllocator1> & lhs, const ::upros_message::YoloDetection_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace upros_message

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::upros_message::YoloDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::upros_message::YoloDetection_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::YoloDetection_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::upros_message::YoloDetection_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::YoloDetection_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::upros_message::YoloDetection_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::upros_message::YoloDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6cdcc6ddbf5ef7d82ed146ef8be8869d";
  }

  static const char* value(const ::upros_message::YoloDetection_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6cdcc6ddbf5ef7d8ULL;
  static const uint64_t static_value2 = 0x2ed146ef8be8869dULL;
};

template<class ContainerAllocator>
struct DataType< ::upros_message::YoloDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "upros_message/YoloDetection";
  }

  static const char* value(const ::upros_message::YoloDetection_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::upros_message::YoloDetection_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"  uint32 seq\n"
"  time stamp\n"
"  string frame_id\n"
"int32 class_id\n"
"int32 center_x\n"
"int32 center_y\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::upros_message::YoloDetection_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::upros_message::YoloDetection_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.seq);
      stream.next(m.stamp);
      stream.next(m.frame_id);
      stream.next(m.class_id);
      stream.next(m.center_x);
      stream.next(m.center_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct YoloDetection_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::upros_message::YoloDetection_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::upros_message::YoloDetection_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "seq: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.seq);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.frame_id);
    s << indent << "class_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.class_id);
    s << indent << "center_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_x);
    s << indent << "center_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.center_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UPROS_MESSAGE_MESSAGE_YOLODETECTION_H
