# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from upros_message/Adc.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Adc(genpy.Message):
  _md5sum = "4fa8ac5d6495ff0c6b2c630d498ca618"
  _type = "upros_message/Adc"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int16 ad1
int16 ad2
int16 ad3
int16 ad4
int16 ad5
int16 ad6
int16 ad7
int16 ad8
int16 ad9
int16 ad10
int16 ad11
int16 ad12"""
  __slots__ = ['ad1','ad2','ad3','ad4','ad5','ad6','ad7','ad8','ad9','ad10','ad11','ad12']
  _slot_types = ['int16','int16','int16','int16','int16','int16','int16','int16','int16','int16','int16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ad1,ad2,ad3,ad4,ad5,ad6,ad7,ad8,ad9,ad10,ad11,ad12

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Adc, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.ad1 is None:
        self.ad1 = 0
      if self.ad2 is None:
        self.ad2 = 0
      if self.ad3 is None:
        self.ad3 = 0
      if self.ad4 is None:
        self.ad4 = 0
      if self.ad5 is None:
        self.ad5 = 0
      if self.ad6 is None:
        self.ad6 = 0
      if self.ad7 is None:
        self.ad7 = 0
      if self.ad8 is None:
        self.ad8 = 0
      if self.ad9 is None:
        self.ad9 = 0
      if self.ad10 is None:
        self.ad10 = 0
      if self.ad11 is None:
        self.ad11 = 0
      if self.ad12 is None:
        self.ad12 = 0
    else:
      self.ad1 = 0
      self.ad2 = 0
      self.ad3 = 0
      self.ad4 = 0
      self.ad5 = 0
      self.ad6 = 0
      self.ad7 = 0
      self.ad8 = 0
      self.ad9 = 0
      self.ad10 = 0
      self.ad11 = 0
      self.ad12 = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12h().pack(_x.ad1, _x.ad2, _x.ad3, _x.ad4, _x.ad5, _x.ad6, _x.ad7, _x.ad8, _x.ad9, _x.ad10, _x.ad11, _x.ad12))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.ad1, _x.ad2, _x.ad3, _x.ad4, _x.ad5, _x.ad6, _x.ad7, _x.ad8, _x.ad9, _x.ad10, _x.ad11, _x.ad12,) = _get_struct_12h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12h().pack(_x.ad1, _x.ad2, _x.ad3, _x.ad4, _x.ad5, _x.ad6, _x.ad7, _x.ad8, _x.ad9, _x.ad10, _x.ad11, _x.ad12))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.ad1, _x.ad2, _x.ad3, _x.ad4, _x.ad5, _x.ad6, _x.ad7, _x.ad8, _x.ad9, _x.ad10, _x.ad11, _x.ad12,) = _get_struct_12h().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12h = None
def _get_struct_12h():
    global _struct_12h
    if _struct_12h is None:
        _struct_12h = struct.Struct("<12h")
    return _struct_12h
